# Glossary {#sec-glossary}

## Console {#glossary-console .unnumbered}

Coming soon.

## Data frame {#glossary-data-frame .unnumbered} 

For our purposes, data frames are just R's term for data set or data table. Data frames are made up of columns (variables) and rows (observations). In R, all columns of a data frame must have the same length.

## Functions {#glossary-functions .unnumbered} 

Coming soon.

  * **Arguments:** Arguments always go _inside_ the parentheses of a function and give the function the information it needs to give us the result we want.   

  * **Pass:** In programming lingo, you _pass_ a value to a function argument. For example, in the funtion call `seq(from = 2, to = 100, by = 2)` we could say that we passed a value of 2 to the `from` argument, we passed a value of 100 to the `to` argument, and we passed a value of 2 to the `by` argument.  

  * **Returns:** Instead of saying, “the `seq()` function _gives us_ a sequence of numbers…” we could say, “the `seq()` function _returns_ us a sequence of numbers…” In programming lingo, functions _return_ one or more results.  
  
## Global environment {#glossary-global-environment .unnumbered}

Coming soon.

## Objects {#glossary-objects .unnumbered}

Coming soon.

## R {#glossary-r .unnumbered}

R is an integrated suite of software facilities for data manipulation, calculation and graphical display. R is very much a vehicle for newly developing methods of interactive data analysis. It has developed rapidly and has been extended by a large collection of packages. However, most programs written in R are essentially ephemeral, written for a single piece of data analysis. @R_Development_Core_Team2020-sj

## R markdown documents {#glossary-r-markdown-documents .unnumbered}

R markdown documents are text files that can be used to clean and analyze your data interactively as well as share your final results in many different formats (e.g., Microsoft Word, PDF, and even websites). R markdown documents weave together R code, narrative text, and multimedia content together into a polished final product. @RStudio2020-yx

## RStudio {#glossary-rstudio .unnumbered}

RStudio is an integrated development environment (IDE) for R. It includes a console, syntax-highlighting editor that supports direct code execution, as well as tools for plotting, history, debugging and workspace management. RStudio is available in open source and commercial editions and runs on the desktop (Windows, Mac, and Linux) or in a browser connected to RStudio Server or RStudio Server Pro (Debian/Ubuntu, Red Hat/CentOS, and SUSE Linux). @RStudio2020-fe

<a name="glossary-test-word">
  <span class="glossary-term">
    Test word
  </span>
</a>

This is a test glossary term that I'm try to reference in @sec-crossrefs without making it a header. I don't want to make it a header because that makes the table of contents really long when rendering to PDF (see [this gh issue](https://github.com/orgs/brad-cannell/projects/3/views/4?pane=issue&itemId=33310870)).

[Test definition]{#glossary-test-definition .glossary-term}

:   This is a test glossary term that I'm try to reference in @sec-crossrefs without making it a header. I don't want to make it a header because that makes the table of contents really long when rendering to PDF (see [this so post](https://stackoverflow.com/questions/76691907/quarto-link-a-word-in-one-qmd-document-to-a-word-in-a-different-qmd-document/76719362#76719362).
