# Publishing {#sec-publishing}

This chapter is about getting the book files on GitHub and creating an HTML version of the book for public consumption. I'm starting with GitHub Pages because it seems like it should be the lowest hanging fruit.

## GitHub repository

The first step to publishing a book online is to put it into a GitHub repository. Originally, I started my book project by creating a new project, clicking new directory, then Quarto book. After creating the book project, I created a repository for it in GitHub and then tried to use GitHub's on-screen instructions to push the book files to the repo. However, I kept getting errors and wasn't ever able to make it work. I feel like this shouldn't be the case and was probably just some weird one-off. So, don't give up on that process just yet.

What I eventually got to work was this process.

-   I created the repo on GitHub (with nothing but a README file) first.
-   I cloned the repo to my computer.
-   I clicked new project \> existing directory.
-   The downside is that RStudio didn't give me the option to make it a Quarto book project.
-   In the terminal, [following this guidance](https://quarto.org/docs/books/), I typed `quarto create-project test_quarto_book --type book`.
    -   Make sure the terminal is set to the project's directory.
-   That added all the built-in book stuff, but in a folder inside the current folder. You can move all of the files you're interested in over if you want. Since I already had the files I had been previously working with (but wasn't able to push to GitHub), I moved them over and worked with them.

## GitHub Pages

Useful websites:

-   https://quarto.org/docs/publishing/github-pages.html

That website discusses three methods for publishing the book with GitHub Pages.

1.  [Render to Docs](https://quarto.org/docs/publishing/github-pages.html#render-to-docs). The easiest and most straightforward. However, checking in the `_book` directory makes for messy diffs.

2.  [The publish command](https://quarto.org/docs/publishing/github-pages.html#publish-command). Requires a little set up on the front end, but gives more control.

3.  [GitHub Action](https://quarto.org/docs/publishing/github-pages.html#github-action). You might prefer this if you want execution and/or rendering to be automatically triggered from commits. However, it seems like the most complicated option.

I'm going with option 2 for now.

## Netlify

Useful websites:

-   https://quarto.org/docs/publishing/netlify.html

That website discusses three methods for publishing the book with Netlify.

1.  [Publish without GitHub](https://quarto.org/docs/publishing/netlify.html#publish-command). This might be the easiest? I guess I should try it out and see how it goes.

    a. [Here is the Netlify site that was created](https://brad-cannell-test-quarto-book.netlify.app/). This seems to work. Maybe just use it until I have a reason not to?
    
    b. The potential downside here seems to be that you have to remember to go into the terminal and type `quarto publish netlify`. The published version isn't automatically updated when you push the repo to GitHub. 

2.  [Publish from GitHub](https://quarto.org/docs/publishing/netlify.html#publish-from-git-provider). At first glance, this seems to be the closest to the process I was using with Bookdown.

3.  [GitHub Action](https://quarto.org/docs/publishing/netlify.html#github-action). You might prefer this if you want execution and/or rendering to be automatically triggered from commits. However, it seems like the most complicated option.

## Publishing Revealjs presentations

2023-07-26: I created these notes while trying to publish the presenation I did for Texas DSHS.

### Useful links

-   [Official publishing Revealjs documentation](https://quarto.org/docs/presentations/revealjs/presenting.html#publishing)
-   [Official publishing HTML basics documentation](https://quarto.org/docs/publishing/)

### What I did to publish

-   When I began this process, I had already created the presentation in an R project.
-   Create a new GitHub repo (with nothing but a README file): https://github.com/brad-cannell/dshs-2023-07-26. 
-   Create a `gh-pages` branch in GitHub.
-   Set the repositories source branch to `gh-pages`. https://quarto.org/docs/publishing/github-pages.html#source-branch
  -  Settings > Pages > Deploy from branch & select gh-pages as the branch.
-   Clone the repo to your computer.
-   Copy and paste all of files I had already created into the newly cloned directory.
-   Rename the qmd file that creates the presentation to `index.qmd`. The `gh-pages` branch will look for an html file named `index`.
-   Render `index.qmd`. `quarto render` in terminal.
-   Commit and push all of the file changes.
-   In the terminal, type `quarto publish gh-pages`.
-   The presentation should appear at `https://brad-cannell.github.io/dshs-2023-07-26`.